### ISSUE TITLE
TS2411 error while building

### ISSUE THREAD

**Issue by xd2** [wusuopu/ts-ga-measurement-protocol#2]
Hi dude. Trying to implement your package. Works great with unit tests.
Nevertheless, got this issue while compiling for my production bundle :

```
$ tsc
node_modules/ga-measurement-protocol/dist/index.d.ts:12:5 - error TS2411: Property 'screen_resolution' of type 'string | undefined' is not assignable to 'string' index type 'string | number'.

12     screen_resolution?: string;
       ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/ga-measurement-protocol/dist/index.d.ts:12

error Command failed with exit code 2.
```
```
$ tsc --version
Version 4.6.2
```
```
$ grep ga-measurement package.json
    "ga-measurement-protocol": "^4.0.0"
```

Good job By the way. very useful library.

**Comment by wusuopu** [comment]
@xd2 `screen_resolution` param is require a string type value, but you give a number type in your code. you need convert your value to a string at before.

**Comment by xd2** [comment]
Thanks for reply @wusuopu ! 

Actually, this is related to your code when compiled in strict mode. Specifically, the TS2411 error occurs when the compiler encounters a module with a missing or incorrectly typed export. This can happen if you are importing a module that does not have the expected export or if the export is not the correct type.

To observe the error on your side, switch to strict mode by adding  the following to you `tsconfig.json`:  
```json
{
  "compilerOptions": {
      "strict": true,
      ...
  }
}
```
You'll get
```
src/index.ts:12:3 - error TS2411: Property 'screen_resolution' of type 'string | undefined' is not assignable to 'string' index type 'string | number'.
```
This is where the error is:
```js
export interface ScreenViewParam {
  firebase_screen: string;
  firebase_previous_screen: string;
  screen_resolution?: string;     // widthxheight
  [key: string]: string|number; // Custom Dimensions
}
```
The [key: string]: string|number; syntax is called an index signature, and it allows you to define additional properties on an object with arbitrary names. However, the TypeScript compiler requires that the property types specified in the index signature are assignable to all properties of the object, which means that they should be a supertype of all the property types.

In your case, the index signature specifies that all additional properties of ScreenViewParam must be either a string or a number, but this might not be the case for all properties. If there is a property with a different type, such as a boolean or an object, the TypeScript compiler will raise the TS2411 error.

To resolve this issue, you need to ensure that all properties of ScreenViewParam, including the ones defined through the index signature, have types that are compatible with the types specified in the interface. You may need to review the code that uses ScreenViewParam and ensure that all properties have the expected type.

Possible fixes, keeping the optionnal screen_resolution:
```typescript
export interface ScreenViewParam {
  firebase_screen: string;
  firebase_previous_screen: string;
  screen_resolution?: string;     // widthxheight
  [key: string]: string|number|undefined; // Custom Dimensions
}
```
Alternative fix, assuming `screen_resolution` is not explicit in interface definition anymore but implicit by the index signature:
``` 
export interface ScreenViewParam {
  firebase_screen: string;
  firebase_previous_screen: string;
  [key: string]: string|number; // Custom Dimensions
}
``` 
I think you'll prefer the first option, i gess your intention was to explicit the developper that `screen_resolution` property is available.

**Comment by xd2** [comment]
I've submitted a pull-request https://github.com/wusuopu/ts-ga-measurement-protocol/pull/3

It enables strict TS and fix related issues.  
Also added a github-actions worflow.  
Eventually improved the syntax color in `readme.md` :-)
